openapi: 3.0.0
info:
  version: 1.0.2
  title: HRIS
  description: The documentation of endpoints for HRIS

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/WAYANPUTRIYANTI1502_1/HRIS/1.0.2
  - url: http://54.198.234.61
  - url: https://hris.belanjalagiyuk.shop

tags:
  - name: Reimbursment
    description: operation about reimbursment
  - name: Cuti
    description: operation about cuti
  - name: Target
    description: operation about target
  - name: Absensi
    description: operation about absensi
paths:
  /reimbursements:
    post:
      tags:
        - Reimbursment
      summary: create reimbursment
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/create_reimbursment"
      responses:
        "201":
          $ref: "#/components/responses/responseSuccessCreate"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"

    get:
      tags:
        - Reimbursment
      description: read all reimbursment
      summary: get all reimbushment
      security:
        - JWTAuth: []
      parameters:
        - name: page
          description: "untuk menentukan page ke berapa"
          required: true
          in: query
          schema:
            type: number
        - name: itemsPerPage
          description: "jumlah users yang ditampilan per halaman"
          required: true
          in: query
          schema:
            type: number
        - name: searchName
          description: "keyword untuk searching berdasarkan nama karyawan"
          required: false
          in: query
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/responseGetAllReimbursment"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
  /reimbursements/{id_reimbursement}:
    put:
      tags:
        - Reimbursment
      summary: update reimbursment
      security:
        - JWTAuth: []
      parameters:
        - name: id_reimbursement
          description: contain id of the reimbursment
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/update_reimbursment_karyawan"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
    get:
      tags:
        - Reimbursment
      summary: reimbursment get by id
      security:
        - JWTAuth: []
      parameters:
        - name: id_reimbursement
          description: contain id of the reimbursment
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      responses:
        "200":
          $ref: "#/components/responses/responseGetByIdReimbursment"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"

    delete:
      tags:
        - Reimbursment
      summary: reimbursment delete by id
      security:
        - JWTAuth: []
      parameters:
        - name: id_reimbursement
          description: contain id of the reimbursment
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"

  /cutis:
    post:
      tags:
        - Cuti
      summary: create cuti
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/create_cuti"
      responses:
        "201":
          $ref: "#/components/responses/responseSuccessCreate"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
    get:
      tags:
        - Cuti
      description: read all cuti
      summary: get all cuti
      security:
        - JWTAuth: []
      responses:
        "200":
          $ref: "#/components/responses/responseGetAllCuti"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"

  /cutis/{id_cuti}:
    put:
      tags:
        - Cuti
      summary: update cuti
      security:
        - JWTAuth: []
      parameters:
        - name: id_cuti
          description: contain id of the cuti
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/create_cuti"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
    delete:
      tags:
        - Cuti
      summary: cuti delete by id
      security:
        - JWTAuth: []
      parameters:
        - name: id_cuti
          description: contain id of the cuti
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"

  /user/{user_id}/targets:
    post:
      tags:
        - Target
      summary: create target
      security:
        - JWTAuth: []
      parameters:
        - name: user_id
          description: contain id of the user
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/create_target"
      responses:
        "201":
          $ref: "#/components/responses/responseSuccessCreate"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
  /targets:
    get:
      tags:
        - Target
      description: read all target
      summary: get all target
      security:
        - JWTAuth: []
      responses:
        "200":
          $ref: "#/components/responses/responseGetAllTargets"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"

  /targets/{target_id}:
    get:
      tags:
        - Target
      summary: target get by id
      security:
        - JWTAuth: []
      parameters:
        - name: target_id
          description: contain id of the target
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
    put:
      tags:
        - Target
      summary: update target
      security:
        - JWTAuth: []
      parameters:
        - name: target_id
          description: contain id of the target
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/create_target"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
    delete:
      tags:
        - Target
      summary: target delete by id
      security:
        - JWTAuth: []
      parameters:
        - name: target_id
          description: contain id of the target
          required: true
          in: path
          schema:
            type: string
            example: "651993b3-fac0-4b92-9ea0-8cba4b66f7e5"
      responses:
        "200":
          $ref: "#/components/responses/responseSuccess"
        "400":
          $ref: "#/components/responses/responseBadRequest"
        "404":
          $ref: "#/components/responses/responseNotFound"
        "500":
          $ref: "#/components/responses/responseFailedInternal"
  /absensis:
    get:
      tags:
        - Absensi
      summary: Get All Absensi
      security:
        - JWTAuth: []
      parameters:
        - name: key
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Response for success retrieve all user data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
              example:
                message: success get all absesnsi data
                data:
                  - id: 13177381ujdhkhu
                    full_name: User1
                    jam_masuk: 07:30:00
                    jam_keluar: 16:30:00
                    date: 2023-09-19
                    check_in: 07:40:56.000
                    check_out: 16:20:56.000
                    overtime_masuk: "10"
                    overtime_keluar: "-10"
                  - id: 19237hdhwhdwh
                    full_name: User2
                    jam_masuk: 07:30:00
                    jam_keluar: 16:30:00
                    date: 2023-09-19
                    check_in: 07:40:56.480
                    check_out: 16:20:56.480
                    overtime_masuk: "10"
                    overtime_keluar: "-10"
                  - id: 19237hdhsyw25whdwh
                    full_name: User3
                    jam_masuk: 07:30:00
                    jam_keluar: 16:30:00
                    date: 2023-09-19
                    check_in: 07:40:56.480
                    check_out: 16:20:56.480
                    overtime_masuk: "10"
                    overtime_keluar: "-10"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Requested resource was not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Internal Server Error
    post:
      tags:
        - Absensi
      summary: Absensi Masuk
      security:
        - JWTAuth: []
      responses:
        "201":
          description: Absen Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_201"
              example:
                message: absensi success
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Requested resource was not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Internal Server Error
  /absensis/{absensi_id}:
    get:
      tags:
        - Absensi
      summary: Get specific absensi information
      security:
        - JWTAuth: []
      parameters:
        - name: absensi_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Success get specific absensi information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_201"
              example:
                message: Success get specific absensi information
                data:
                  id: 123wdgwdhwi
                  employee_name: user 1
                  jam_masuk: 07:30:00
                  jam_keluar: 16:30:00
                  date: 2023-09-19
                  check_in: 07:40:56.480
                  check_out: 16:20:56.480
                  overtime_masuk: "10"
                  overtime_keluar: "-10"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Requested resource was not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Internal Server Error
    put:
      tags:
        - Absensi
      summary: Absensi Pulang
      security:
        - JWTAuth: []
      parameters:
        - name: absensi_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "201":
          description: Absen Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_201"
              example:
                message: absensi success
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Requested resource was not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObj"
              example:
                message: Internal Server Error
#==================================#
# component
#==================================#
components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "use Token"

  schemas:
    create_reimbursment:
      type: object
      properties:
        tipe:
          type: string
          description: "example: operation"
        cash_out_date:
          type: string
          description: "example: 18-06-2023"
        nominal:
          type: integer
          description: "example: 10000"
        description:
          type: string
          description: "example: peralatan kantor"
        image:
          type: string
          format: binary
          description: "allowed file extension: jpg, png, jpeg"
    ResponseObj:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
    inline_response_200:
      allOf:
        - type: object
        - $ref: "#/components/schemas/ResponseArr"
    inline_response_201:
      allOf:
        - type: object
        - $ref: "#/components/schemas/ResponseObj"
    ResponseArr:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            type: object
    create_cuti:
      type: object
      properties:
        tipe_cuti:
          type: string
          description: "example: melahirkan"
        status:
          type: string
          description: "example: reject"
        jumlah_cuti:
          type: integer
          description: "example: 18"
        batasan_cuti:
          type: string
          description: "example: 90"
        description:
          type: string
          description: "example: cuti melahirkan"
        persetujuan:
          type: string
          description: "example: reject"
        start_cuti:
          type: string
          description: "example: 10-09-2023"
        end_cuti:
          type: string
          description: "example: 28-09-2023"
        image:
          type: string
          format: binary
          description: "allowed file extension: jpg, png, jpeg"

    create_target:
      type: object
      properties:
        konten_target:
          type: string
          description: "example: reimbursment pekerja"
        status:
          type: string
          description: "example: not-completed"
        divisi_id:
          type: integer
          description: "example: 68a83bd8-a392-4877-b10f-f0025185"
        user_id_pembuat:
          type: string
          description: "example: 54396f94-07b8-4450-8105-7c"
        user_id_penerima:
          type: string
          description: "example: 27567353-9507-43d3-b08c-e"
        due_date:
          type: string
          description: "example: 25-09-2023"
        image:
          type: string
          format: binary
          description: "allowed file extension: jpg, png, jpeg"

    update_reimbursment_karyawan:
      type: object
      properties:
        tipe:
          type: string
        cash_out_date:
          type: string
          description: "example: 18-09-2023"
        nominal:
          type: integer
          description: "example: 10000"
        description:
          type: string
          description: "example: peralatan kantor"
        status:
          type: string
          description: "example: approve"
        persetujuan:
          type: string
          description: "example: approve"
        image:
          type: string
          format: binary
          description: "allowed file extension: jpg, png, jpeg"
  responses:
    responseSuccess:
      description: failed
      content:
        application/json:
          schema:
            type: object
            properties:
              "code":
                type: integer
                format: int64
                example: 200
              "message":
                type: string
                description: A human-readable message describing the result.
                example: success
              "data":
                type: object
                example: null

    responseSuccessCreate:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              "code":
                type: integer
                format: int64
                example: 201
              "message":
                type: string
                description: A human-readable message describing the result.
                example: created
              "data":
                type: object
                example: null

    responseGetByIdReimbursment:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
                example: 200
              message:
                type: string
                example: "success get reimbursment by id"
              data:
                type: object
                properties:
                  id:
                    type: string
                    example: "0bab9e2b-dc1c-4d95-aece-06e9e28707d4"
                  name:
                    type: string
                    example: "Sandi Gunawan"
                  tipe:
                    type: string
                    example: "operational"
                  cash_out_date:
                    type: string
                    example: "09-09-2023"
                  nominal:
                    type: integer
                    example: 180000
                  description:
                    type: string
                    example: "sewa hotel"
                  image:
                    type: string
                    example: "https://res.cloudinary.com/duklipjcj/image/upload/v1693188884/292691.41653526-bd1a-485c-985b-885eba8ad3c1.%2CATAP.jpg.jpg"
                  status:
                    type: string
                    example: "pending"
    responseGetByIdTargets:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
                example: 200
              message:
                type: string
                example: "success get all targets"
              data:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    konten_target:
                      type: string
                    status:
                      type: string
                    devisi_id:
                      type: string
                    user_id_pembuat:
                      type: string
                    user_id_penerima:
                      type: string
                    due_date:
                      type: string
                    proofs:
                      type: string
                example:
                  - id: 0d53eb66-a96b-4c32-8e5e-13158e2006a4
                    konten_target: reimbursment pekerja
                    status: not completed
                    devisi_id: 68a83bd8-a392-4877-b10f-f00251850cb8
                    user_id_pembuat: 54396f94-07b8-4450-8105-7c4472bf8701
                    user_id_penerima: 27567353-9507-43d3-b08c-eea2c8c094fb
                    due_date: 25-09-2023
    responseGetAllReimbursment:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
                example: 200
              message:
                type: string
                example: "success get all reimbursment"
              next:
                type: boolean
                example: true
              data:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    tipe:
                      type: string
                    cash_out_date:
                      type: string
                    nominal:
                      type: integer
                    description:
                      type: string
                    image:
                      type: string
                    status:
                      type: string
                example:
                  - id: "0bab9e2b-dc1c-4d95-aece-06e9e28707d4"
                    name: "Sandi Gunawan"
                    tipe: "operational"
                    cash_out_date: "09-09-2023"
                    nominal: 180000
                    description: "sewa hotel"
                    image: "https://res.cloudinary.com/duklipjcj/image/upload/v1693188884/292691.41653526-bd1a-485c-985b-885eba8ad3c1.%2CATAP.jpg.jpg"
                    status: "pending"
                  - id: "0bab9e2b-dc1c-4d95-aece-06e9e218207d3"
                    name: "Maria Sari"
                    tipe: "operational"
                    cash_out_date: "10-09-2023"
                    nominal: 340000
                    description: "beli peralatan"
                    image: "https://res.cloudinary.com/duklipjcj/image/upload/v1693188884/292691.41653526-bd1a-485c-985b-885eba8ad3c1.%2CATAP.jpg.jpg"
                    status: "approve"
                  - id: "0bab9e2b-dc1c-4d95-aece-06e9e287079203"
                    name: "Melita"
                    tipe: "operational"
                    cash_out_date: "24-09-2023"
                    nominal: 170000
                    description: "sewa hotel"
                    image: "https://res.cloudinary.com/duklipjcj/image/upload/v1693188884/292691.41653526-bd1a-485c-985b-885eba8ad3c1.%2CATAP.jpg.jpg"
                    status: "pending"
    responseGetAllTargets:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
                example: 200
              message:
                type: string
                example: "success get all targets"
              data:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    konten_target:
                      type: string
                    status:
                      type: string
                    devisi_id:
                      type: string
                    user_id_pembuat:
                      type: string
                    user_id_penerima:
                      type: string
                    due_date:
                      type: string
                    proofs:
                      type: string
                example:
                  - id: 0d53eb66-a96b-4c32-8e5e-13158e2006a4
                    konten_target: reimbursment pekerja
                    status: not completed
                    devisi_id: 68a83bd8-a392-4877-b10f-f00251850cb8
                    user_id_pembuat: 54396f94-07b8-4450-8105-7c4472bf8701
                    user_id_penerima: 27567353-9507-43d3-b08c-eea2c8c094fb
                    due_date: 25-09-2023
                  - id: 10b28ed5-59dc-4383-ae02-154a2516d40a
                    konten_target: "Pengelolaan Utang "
                    status: not completed
                    devisi_id: b256efa8-56ea-11ee-9bcf-fcc1d3dbd38e
                    user_id_pembuat: b03afa83-cf52-494b-b3d2-9cd89a4867d5
                    user_id_penerima: 54396f94-07b8-4450-8105-7c4472bf8701
                    due_date: 30-09-2023
                  - id: 473a2b0e-cec1-4ede-abb0-4f3237b0889e
                    konten_target: gaji karyawan
                    status: not completed
                    devisi_id: 68a83bd8-a392-4877-b10f-f00251850cb8
                    user_id_pembuat: 54396f94-07b8-4450-8105-7c4472bf8701
                    user_id_penerima: 27567353-9507-43d3-b08c-eea2c8c094fb
                    due_date: 25-09-2023

    responseGetAllCuti:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
                example: 200
              message:
                type: string
                example: "success get all cuti"
              data:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    tipe_cuti:
                      type: string
                    status:
                      type: string
                    jumlah_cuti:
                      type: integer
                    description:
                      type: integer
                    persetujuan:
                      type: string
                    url_pendukung:
                      type: string
                    user_id:
                      type: string
                example:
                  - id: "0bab9e2b-dc1c-4d95-aece-06e9e28707d4"
                    name: "Sandi Gunawan"
                    tipe_cuti: "tahunan"
                    status: "pending"
                    jumlah_cuti: 23
                    description: "cuti tahunan"
                    persetujuan: "pending"
                    url_pendukung: "https://res.cloudinary.com/duklipjcj/image/upload/v1693188884/292691.41653526-bd1a-485c-985b-885eba8ad3c1.%2CATAP.jpg.jpg"
                    user_id: "0bab9e2b-dc1c-4d95-aece-06e9e28707d1"
                  - id: "0bab9e2b-dc1c-4d95-aece-06e9e28707d4"
                    name: "Sandi Gunawan"
                    tipe_cuti: "tahunan"
                    status: "pending"
                    jumlah_cuti: 23
                    description: "cuti tahunan"
                    persetujuan: "pending"
                    url_pendukung: "https://res.cloudinary.com/duklipjcj/image/upload/v1693188884/292691.41653526-bd1a-485c-985b-885eba8ad3c1.%2CATAP.jpg.jpg"
                    user_id: "0bab9e2b-dc1c-4d95-aece-06e9e28707d1"

    responseBadRequest:
      description: failed
      content:
        application/json:
          schema:
            type: object
            properties:
              "code":
                type: integer
                format: int64
                example: 400
              "message":
                type: string
                description: A human-readable message describing the result.
                example: operation failed, request resource not valid
              "data":
                type: object
                example: null

    responseNotFound:
      description: resouse was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              "code":
                type: integer
                description: HTTP status code (e.g., 200 for success).
                example: 404
              "message":
                type: string
                description: A human-readable message describing the result.
                example: operation failed, resource not found
              "data":
                type: object
                example: null

    responseFailedInternal:
      description: failed
      content:
        application/json:
          schema:
            type: object
            properties:
              "code":
                type: integer
                format: int64
                example: 500
              "message":
                type: string
                example: operation failed, internal server error
              "data":
                type: object
                example: null
